name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'   # tag 触发正式 release
    branches:
      - main
      - dev
      - dev_huangzhenming
      - feat/**
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build
          ls -al dist/

      - name: Determine version
        id: version
        run: |
          # tag push
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          else
            # branch push
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: Zip python package
        run: |
          mkdir -p upload
          zip -j upload/k230-flash-${{ env.VERSION }}.zip dist/*

      # tag release 上传到 GitHub Release
      - name: Upload Python Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: upload/k230-flash-${{ env.VERSION }}.zip
          prerelease: true

      # nightly 上传到 workflow artifact
      - name: Upload Python Nightly Artifact
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: k230-flash-${{ env.VERSION }}
          path: upload/k230-flash-${{ env.VERSION }}.zip

  gui-release:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          label: ubuntu
        - os: windows-2022
          label: windows
        - os: macos-13
          label: macos
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyinstaller and project
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pip install -e .

      - name: Install UPX / 7zip (Windows only)
        if: matrix.os == 'windows-2022'
        run: |
          choco install upx -y
          choco install 7zip -y

      - name: Install appimagetool (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y appstream fuse libfuse2
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool

      - name: Determine version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          else
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: Build GUI with pyinstaller
        run: |
          cd src/gui
          pyinstaller --clean k230_flash_gui.spec

      # Windows zip
      - name: Package GUI (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          mkdir -p upload
          cd src/gui/dist
          7z a ../../../upload/k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}.zip k230_flash_gui.exe

      # macOS dmg
      - name: Package GUI (macOS)
        if: matrix.os == 'macos-13'
        run: |
          mkdir -p upload
          cd src/gui/dist
          hdiutil create -volname "k230_flash_gui" \
            -srcfolder "k230_flash_gui.app" \
            -ov -format UDZO \
            "../../../upload/k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}.dmg"

      # Ubuntu AppImage
      - name: Package GUI (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p upload
          cd src/gui/dist
          mkdir -p AppDir/usr/bin
          cp k230_flash_gui AppDir/usr/bin/
          # 从源目录复制assets，因为PyInstaller已经将其嵌入到可执行文件中
          # 但AppImage仍需要图标文件
          mkdir -p AppDir/usr/share/pixmaps
          cp ../assets/k230_flash_gui_logo.png AppDir/usr/share/pixmaps/k230_flash_gui.png
          cat > AppDir/k230_flash_gui.desktop <<EOF
          [Desktop Entry]
          Type=Application
          Name=k230_flash_gui
          Exec=k230_flash_gui
          Icon=k230_flash_gui
          Categories=Utility;
          EOF
          # 复制图标到AppDir根目录
          cp ../assets/k230_flash_gui_logo.png AppDir/k230_flash_gui.png
          # 使用--no-appstream参数避免AppStream验证问题，并设置ARCH环境变量
          ARCH=x86_64 appimagetool --no-appstream AppDir "../../../upload/k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}.AppImage"

      - name: Upload GUI Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
          prerelease: true

      - name: Upload GUI Nightly Artifact
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}
          path: upload/*
