name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build
          ls -al dist/

      - name: Determine version1
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          else
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: Zip1 python package
        run: |
          mkdir -p upload
          zip -j upload/k230-flash-${{ env.VERSION }}.zip dist/*

      # - name: Upload Python Release Asset
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: upload/k230-flash-${{ env.VERSION }}.zip
      #     prerelease: true

      # - name: Upload Python Nightly Artifact
      #   if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: k230-flash-${{ env.VERSION }}
      #     path: upload/k230-flash-${{ env.VERSION }}.zip

  gui-release:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          label: ubuntu
        # - os: windows-2022
        #   label: windows
        # - os: macos-13
        #   label: macos
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UPX / 7zip (Windows only)
        if: matrix.label == 'windows'
        run: |
          choco install upx -y
          choco install 7zip -y

      # - name: Install 7zip (Ubuntu only)
      #   if: matrix.label == 'ubuntu'
      #   run: |
      #     sudo apt-get install p7zip-full -y

      # Determine version
      - name: Determine version
        id: version
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          else
            VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"
          echo "JimmyDebug 1"

      # Ubuntu AppImage using Docker + FUSE
      - name: Package GUI (Linux with Docker & FUSE)
        if: matrix.label == 'ubuntu22'
        run: |
          mkdir -p upload
          docker run --rm \
            --privileged \
            --device /dev/fuse \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            python:3.11-bullseye \
            bash -c "
              apt-get update && apt-get install -y build-essential wget curl git libfuse2 fuse
              pip install --upgrade pip
              pip install pyinstaller
              pip install -r requirements.txt
              pip install -e .

              wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
              chmod +x /usr/local/bin/appimagetool

              # 构建 GUI
              cd src/gui
              pyinstaller --clean k230_flash_gui.spec

              # 创建 AppDir
              APPDIR=\$(pwd)/AppDir
              rm -rf \$APPDIR
              mkdir -p \$APPDIR/usr/bin
              cp dist/k230_flash_gui/* \$APPDIR/usr/bin/

              mkdir -p \$APPDIR/usr/share/pixmaps
              cp -r assets \$APPDIR/usr/share/

              echo '[Desktop Entry]'          >  \$APPDIR/k230_flash_gui.desktop
              echo 'Type=Application'        >> \$APPDIR/k230_flash_gui.desktop
              echo 'Name=k230_flash_gui'     >> \$APPDIR/k230_flash_gui.desktop
              echo 'Exec=/usr/bin/k230_flash_gui' >> \$APPDIR/k230_flash_gui.desktop
              echo 'Icon=k230_flash_gui'     >> \$APPDIR/k230_flash_gui.desktop
              echo 'Categories=Utility;'     >> \$APPDIR/k230_flash_gui.desktop

              cp assets/k230_flash_gui_logo.png \$APPDIR/k230_flash_gui.png

              # 打包 AppImage
              ARCH=x86_64 appimagetool --no-appstream \$APPDIR /workspace/upload/k230_flash_gui-ubuntu-${{ env.VERSION }}.AppImage
            "

      - name: Package GUI (Linux with Docker & FUSE)
        if: matrix.label == 'ubuntu23'
        run: |
          mkdir -p upload
          docker run --rm \
            --privileged \
            --device /dev/fuse \
            --user root \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            --name qt6 \
            stateoftheartio/qt6:6.6-gcc-aqt \
            bash -c "
              apt-get update && apt-get install -y build-essential wget curl git libfuse2 fuse libgl-dev libvulkan-dev libssl-dev libudev-dev fuse file software-properties-common
              
              add-apt-repository ppa:deadsnakes/ppa -y
              apt-get update && apt-get install -y python3.11 python3.11-dev python3.11-venv python3.11-distutils

              # 设置默认 python3 指向 python3.11
              update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
              update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
              update-alternatives --set python3 /usr/bin/python3.11

              # 用 python3.11 正确安装 pip 到 /usr/local/bin
              curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

              # 验证 pip 是否可用
              python3 -m pip --version

              # 后续就用 python3 -m pip 而不是裸 pip 更安全
              python3 -m pip install --upgrade pip
              python3 -m pip install pyinstaller
              python3 -m pip install -r requirements.txt
              python3 -m pip install -e .
              pip install --upgrade pip
              pip install pyinstaller
              pip install -r requirements.txt
              pip install -e .

              wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
              chmod +x /usr/local/bin/appimagetool

              # 构建 GUI
              cd src/gui
              pyinstaller --clean k230_flash_gui.spec

              echo "请复制文件，等待60秒"
              sleep 60
              echo  "开始创建 AppDir"

              # 创建 AppDir
              APPDIR=\$(pwd)/AppDir
              rm -rf \$APPDIR
              mkdir -p \$APPDIR/usr/bin
              cp dist/k230_flash_gui \$APPDIR/usr/bin/

              mkdir -p \$APPDIR/usr/share/pixmaps
              cp -r assets \$APPDIR/usr/share/

              echo '[Desktop Entry]'          >  \$APPDIR/k230_flash_gui.desktop
              echo 'Type=Application'        >> \$APPDIR/k230_flash_gui.desktop
              echo 'Name=k230_flash_gui'     >> \$APPDIR/k230_flash_gui.desktop
              echo 'Exec=/usr/bin/k230_flash_gui' >> \$APPDIR/k230_flash_gui.desktop
              echo 'Icon=k230_flash_gui'     >> \$APPDIR/k230_flash_gui.desktop
              echo 'Categories=Utility;'     >> \$APPDIR/k230_flash_gui.desktop

              cp assets/k230_flash_gui_logo.png \$APPDIR/k230_flash_gui.png

              # 打包 AppImage
              ARCH=x86_64 appimagetool --no-appstream \$APPDIR /workspace/upload/k230_flash_gui-ubuntu-${{ env.VERSION }}.AppImage
            "

      - name: Package GUI (Linux with Docker & FUSE)
        if: matrix.label == 'ubuntu'
        run: |
          mkdir -p upload
          docker run --rm \
            --privileged \
            --device /dev/fuse \
            --user root \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            --name qt6 \
            qt6-pyside6-appimage-builder:1.0 \
            bash -c '
              # add-apt-repository ppa:deadsnakes/ppa -y
              # apt-get update && apt-get install -y python3.11 python3.11-dev python3.11-venv python3.11-distutils
              apt-get update && apt-get install -y libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin shared-mime-info

              # # 设置默认 python3 指向 python3.11
              # update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
              # update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
              # update-alternatives --set python3 /usr/bin/python3.11

              # # 用 python3.11 正确安装 pip 到 /usr/local/bin
              # curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

              # # 验证 pip 是否可用
              # python3 -m pip --version

              pip install --upgrade pip
              pip install pyinstaller
              pip install -r requirements.txt
              pip install -e .

              wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
              chmod +x /usr/local/bin/appimagetool

              # 构建 GUI
              cd src/gui
              pyinstaller --clean -y k230_flash_gui.spec

              echo "请复制文件，等待30秒"
              # sleep 30
              echo  "开始创建 AppDir"

              # 创建 AppDir
              APPDIR=$(pwd)/AppDir
              rm -rf $APPDIR
              mkdir -p $APPDIR/usr/bin
              cp -r dist/k230_flash_gui/* $APPDIR/usr/bin/
              cp -r package/AppDir/*  $APPDIR
              

              echo "JimmyDebug 3"
              mkdir -p $APPDIR/usr/share/pixmaps
              cp -r assets $APPDIR/usr/share/
              
              mkdir -p $APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders
              cp -r /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/* $APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/

              cp /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders $APPDIR/usr/bin/
              $APPDIR/usr/bin/gdk-pixbuf-query-loaders > $APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

              echo "JimmyDebug 4"
              # 打包 AppImage
              ARCH=x86_64 appimagetool --no-appstream $APPDIR /workspace/k230_flash_gui-ubuntu-${{ env.VERSION }}.AppImage
              echo "JimmyDebug 5"
              echo "请复制文件，等待120秒"
              sleep 60
              echo  "开始创建 AppDir"
            '
      
      # PyInstaller 构建 GUI
      # - name: Build GUI with pyinstaller
      #   run: |
      #     pip install --upgrade pip
      #     pip install pyinstaller
      #     pip install -r requirements.txt
      #     pip install -e .
      #     cd src/gui
      #     pyinstaller --clean k230_flash_gui.spec
      #     echo "JimmyDebug 2"


      # # zip
      # - name: Package GUI Zip
      #   run: |
      #     mkdir -p upload
      #     cd src/gui/dist
      #     7z a ../../../upload/k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}.zip *

      # 上传 release
      # - name: Upload GUI Release Asset
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: upload/*
      #     prerelease: true

      # - name: Upload GUI Nightly Artifact
      #   if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: k230_flash_gui-${{ matrix.label }}-${{ env.VERSION }}
      #     path: upload/*
